services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.7
    environment:
      # Настройка прокси для работы за обратным прокси
      KC_PROXY: edge
      # Данные администратора (KC_BOOTSTRAP_* - более новый формат)
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # Настройки хоста и портов
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: "false"           # Отключает строгую проверку hostname
      KC_HOSTNAME_STRICT_HTTPS: "false"     # Разрешает HTTP соединения
      KC_HOSTNAME_PORT: 8080                # Порт для внешних соединений
      # Включение HTTP и отключение HTTPS для dev-режима
      KC_HTTP_ENABLED: 'true'
      # Включение эндпоинтов мониторинга
      KC_HEALTH_ENABLED: 'true'             # Включает health check эндпоинты
      KC_METRICS_ENABLED: 'true'            # Включает метрики Prometheus
      # Уровень логирования
      KC_LOG_LEVEL: INFO
      # Настройки подключения к PostgreSQL
      KC_DB: postgres                       # Тип базы данных
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak  # URL подключения к БД
      KC_DB_USERNAME: keycloak              # Пользователь БД
      KC_DB_PASSWORD: keycloak_password     # Пароль БД
    depends_on:
      postgres:
        condition: service_healthy          # Ждет готовности PostgreSQL
    healthcheck:
      # Проверка доступности через health endpoint
      test: ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/live']
      interval: 5s                          # Интервал проверки
      timeout: 5s                           # Таймаут проверки
      retries: 30                           # Количество попыток
    command: ['start-dev', '--http-port', '8080'] # Запуск в dev-режиме на порту 8080
    ports:
      - 8080:8080                           # Проброс порта для веб-интерфейса
    networks:
      - keycloak-network

  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.0
    environment:
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_CLIENT_ID: yandex-s3-client
      OAUTH2_PROXY_CLIENT_SECRET: your-client-secret
      OAUTH2_PROXY_REDIRECT_URL: https://yourdomain.com/oauth2/callback
      OAUTH2_PROXY_OIDC_ISSUER_URL: http://keycloak:8080/realms/yandex-s3
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_COOKIE_SECRET: your-cookie-secret-32-bytes-long
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_UPSTREAMS: http://nginx:80
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
      OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
    networks:
      - keycloak-network
    depends_on:
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:4180/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - keycloak-network
    depends_on:
      oauth2-proxy:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:

networks:
  keycloak-network:
    driver: bridge
