services:
  minio-client:
    image: docker.io/bitnami/minio-client:latest
    container_name: minio-client
    environment:
      MINIO_SERVER_ACCESS_KEY: "MINIO_SERVER_ACCESS_KEY"
      MINIO_SERVER_SECRET_KEY: "MINIO_SERVER_SECRET_KEY"
      MINIO_SERVER_HOST: storage.yandexcloud.net
      MINIO_SERVER_PORT_NUMBER: 443
      MINIO_SERVER_USE_SSL: "true"
    volumes:
      - ./s3-config:/opt/bitnami/minio-client/.mc
    networks:
      - s3-network

  # FileBrowser для работы с S3 как с файловой системой
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: s3-filebrowser
    ports:
      - "8081:80"
    environment:
      FB_DATABASE: /database/filebrowser.db
      FB_CONFIG: /config/settings.json
    volumes:
      - ./filebrowser-config:/config
      - ./filebrowser-db:/database
      - s3_mount:/srv
    networks:
      - s3-network

  # S3 FUSE mount для монтирования как обычной файловой системы
  s3fs:
    image: alpine:latest
    container_name: s3fs-mount
    privileged: true
    environment:
      AWS_ACCESS_KEY_ID: access_key
      AWS_SECRET_ACCESS_KEY: secret_key
      S3_BUCKET: your-bucket-name
      S3_URL: https://storage.yandexcloud.net
    volumes:
      - s3_mount:/mnt/s3
      - ./s3fs-config:/etc/passwd-s3fs:ro
    command: |
      sh -c "
        apk add --no-cache s3fs-fuse &&
        echo 'access_key:secret_key' > /etc/passwd-s3fs &&
        chmod 600 /etc/passwd-s3fs &&
        s3fs your-bucket-name /mnt/s3 -o passwd_file=/etc/passwd-s3fs,url=https://storage.yandexcloud.net,use_path_request_style,allow_other &&
        tail -f /dev/null
      "
    restart: unless-stopped
    networks:
      - s3-network
    profiles:
      - s3fs

volumes:
  minio_data:
    driver: local
  s3_mount:
    driver: local

networks:
  s3-network:
    driver: bridge