apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-ui-config
  namespace: default
data:
  S3_ENDPOINT: "https://s3.amazonaws.com"  # или ваш S3-совместимый endpoint
  S3_REGION: "us-east-1"
  S3_BUCKET: "your-bucket-name"
